### ISSUE TITLE
I have got crash on production app

### ISSUE THREAD

**Issue by ravisharma46** [razorpay/razorpay-android-custom-sample-app#53] opened 2021-06-30 15:05 UTC
Caused by java.lang.NullPointerException
println needs a message

android.util.Log.d (Log.java:181)
com.razorpay.l.a (l.java:2024)
com.razorpay.BaseRazorpay.initRazorpay (BaseRazorpay.java:175)
com.razorpay.BaseRazorpay.<init> (BaseRazorpay.java:154)
com.razorpay.OtpelfBaseRazorpay.<init> (OtpelfBaseRazorpay.java:15)
com.razorpay.Razorpay.<init> (Razorpay.java:46)
com.inventia.app.ui.activities.PaymentActivity.initRazorpay (PaymentActivity.java:397)
com.inventia.app.ui.activities.PaymentActivity.onCreate (PaymentActivity.java:115)

Please look into this asap @vivekshindhe

**Comment by vivekshindhe** [comment] 2021-06-30 18:12
@ravisharma46 Will need some reproducible steps for this? Did you update the SDK? Is this constant or intermittent?

**Comment by vivekshindhe** [comment] 2021-06-30 18:14
@ravisharma46 also, how are you setting the apiKey?

**Comment by ravisharma46** [comment] 2021-06-30 18:54
@vivekshindhe it is intermittent and we are setting apiKey threw a backend API call.

**Comment by vivekshindhe** [comment] 2021-06-30 18:57
The error is occurring because the key is empty.

**Comment by ravisharma46** [comment] 2021-06-30 19:09
ok i will check with my backend team. thanks for the help @vivekshindhe

**Comment by vivekshindhe** [comment] 2021-07-05 04:38
@ravisharma46 hoping this was resolved. Closing the issue. Please comment here in case it wasn't. Thank you.

**Closed by vivekshindhe** 2021-07-05 04:38 UTC
